namespace Ion.Numeral;

public enum Uple
{
    Single = 1,
    Double,
    Triple,
    Quadruple,
    Quintuple,
    Sextuple,
    Septuple,
    Octuple,
    Nonuple,
    Decuple,
    Undecuple,
    Duodecuple,
    Tredecuple,
    Quattuordecuple,
    Quindecuple,
    Sexdecuple,
    Septendecuple,
    Octodecuple,
    Novemdecuple,
    Vigintuple,
    Unvigintuple,
    Duovigintuple,
    Trevigintuple,
    Quattuorvigintuple,
    Quinvigintuple,
    Sexvigintuple,
    Septenvigintuple,
    Octovigintuple,
    Novemvigintuple,
    Trigintuple,
    Quadragintuple = 40,
    Quinquagintuple = 50,
    Sexagintuple = 60,
    Septuagintuple = 70,
    Octogintuple = 80,
    Nongentuple = 90,
    Centuple = 100,
    Milluple = 1000
}